name: sid_modular
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  sid_d_d:
    path: 'C:/DEVS/sid_d_d'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
